export const FETCH_RECIPES_START = 'FETCH_RECIPES_START';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAIL = 'FETCH_RECIPES_FAIL';

export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_START = 'FETCH_AUTHORS_START';
export const FETCH_AUTHORS_FAIL = 'FETCH_AUTHORS_FAIL';

export const CREATE_RECIPE = 'CREATE_RECIPE';

export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';

export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS';

export const DELETE_RECIPE_OPTIMISTIC = 'DELETE_RECIPE_OPTIMISTIC';
