export const FETCH_RECIPES_START = 'FETCH_RECIPES_START';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAIL = 'FETCH_RECIPES_FAIL';

export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_START = 'FETCH_AUTHORS_START';
export const FETCH_AUTHORS_FAIL = 'FETCH_AUTHORS_FAIL';


export const CREATE_RECIPE = 'CREATE_RECIPE';


export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
